// DNA Algorith Queue

// Default static queue Data - this will be updated in real time from Firestore
let queue = [
['academic', 0, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'ca', '', '', '', '', '', '', 'Graph Theory Tutor', '', '', '', '', '', '', ],
['add clicks', 1, 1, 'cn', '', '', '', '', '', '', 'Add counter of clicks for activation tags', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['admin', 2, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'us', '', '', '', '', '', '', 'MySQL Database Admin', '', '', '', '', '', '', ],
['agile', 3, 1, 'us', '', '', '', '', '', '', 'New agile team trust', '', '', '', '', '', '', 1, 'ro', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['algorithm', 4, 1, 'ca', '', '', '', '', '', '', 'Find all isomorphisms of a graph', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['app', 5, 1, 'ro', '', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['apps', 6, 1, 'hu', '', '', '', '', '', '', 'JIRA Issues translator to Social DNA', '', '', '', '', '', '', 1, 'es', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['apps script', 7, 1, 'in', '', '', '', '', '', '', 'Social DNA Translator to SQL Google', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['Apps Script', 8, 1, 'il', '', '', '', '', '', '', 'Script to transform text in a list of sentences', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['archive', 9, 1, 'ca', '', '', '', '', '', '', 'Create archive from the problems entered this weekend', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['automation', 10, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2, 'cn', 'ru', '', '', '', '', '', 'Agile planning automation scripts', 'Social DNA consulting', '', '', '', '', '', ],
['availability', 11, 1, 'ca', '', '', '', '', '', '', 'Project team communication', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['campaign', 12, 1, 'us', '', '', '', '', '', '', 'Einstein to POTUS letter transformation', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['clicks', 13, 1, 'ru', '', '', '', '', '', '', 'Add counter of clicks for activation tags', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['cloud', 14, 1, 'ca', '', '', '', '', '', '', 'Google Social DNA Editor', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['code', 15, 1, 'us', '', '', '', '', '', '', 'JS timer function to change DOM text', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['collaboration', 16, 1, 'us', '', '', '', '', '', '', 'Project team communication', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['communication', 17, 2, 'gb', 'il', '', '', '', '', '', 'Project team communication', 'W3AI Communication materials', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['communities', 18, 1, 'pt', '', '', '', '', '', '', 'W3AI Communication materials', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['content', 19, 2, 'ca', 'us', '', '', '', '', '', '3 Jars', 'Secret sauce sell 4 liters', '', '', '', '', '', 2, 'es', 'in', '', '', '', '', '', 'Clear Pour', 'Pouring liquids', '', '', '', '', '', ],
['counting', 20, 1, 'ca', '', '', '', '', '', '', 'Add counter of clicks for activation tags', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['data', 21, 1, 'us', '', '', '', '', '', '', 'Create archive from the problems entered this weekend', '', '', '', '', '', '', 1, 'pt', '', '', '', '', '', '', 'MySQL Database Admin', '', '', '', '', '', '', ],
['database', 22, 1, 'ru', '', '', '', '', '', '', 'Create REST API for Postgres Database', '', '', '', '', '', '', 1, 'pl', '', '', '', '', '', '', 'MySQL Database Admin', '', '', '', '', '', '', ],
['definition', 23, 1, 'ca', '', '', '', '', '', '', 'About Social DNA Language', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['definitions', 24, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'ro', '', '', '', '', '', '', 'Social DNA consulting', '', '', '', '', '', '', ],
['delivery', 25, 1, 'us', '', '', '', '', '', '', 'Large Pizza, 3 Toppings', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['design', 26, 2, 'gb', 'cn', '', '', '', '', '', 'mobile ready forms', 'Search engine look for problems and services', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['development', 27, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'ca', '', '', '', '', '', '', 'Vertx Developer', '', '', '', '', '', '', ],
['devops', 28, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'us', '', '', '', '', '', '', 'DevOps scripts templating', '', '', '', '', '', '', ],
['digital', 29, 1, 'us', '', '', '', '', '', '', 'Digital Front end display for ShiftKey Labs', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['display', 30, 1, 'ru', '', '', '', '', '', '', 'Digital Front end display for ShiftKey Labs', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['docs', 31, 2, 'ca', 'cn', '', '', '', '', '', 'W3AI organization structure like W3C', 'W3AI Communication materials', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['dom', 32, 1, 'us', '', '', '', '', '', '', 'JS timer function to change DOM text', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['dynamic scheduling', 33, 1, 'us', '', '', '', '', '', '', 'Google App scripts to replicate Dynamic Scheduling in Google Sheets', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['editor', 34, 2, 'gb', 'ru', '', '', '', '', '', 'Google Social DNA Editor', 'Mobile Social DNA Editor for Office 365', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['emails', 35, 1, 'pt', '', '', '', '', '', '', 'Project team communication', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['excel', 36, 2, 'ca', 'pt', '', '', '', '', '', 'Excel Social DNA verb template', 'Excel Social DNA noun template', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['favicon', 37, 1, 'ru', '', '', '', '', '', '', 'W3AI favicon', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['food', 38, 1, 'ro', '', '', '', '', '', '', 'Large Pizza, 3 Toppings', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['funding', 39, 1, 'cn', '', '', '', '', '', '', 'Einstein to POTUS letter transformation', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['gadget', 40, 1, 'fr', '', '', '', '', '', '', 'Digital Front end display for ShiftKey Labs', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['google', 41, 3, 'de', 'hu', 'jp', '', '', '', '', 'Google Sheets Social DNA verb template', 'Google Sheets Social DNA noun template', 'Social DNA Translator to SQL Google', '', '', '', '', 1, 'in', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['Google', 42, 1, 'eg', '', '', '', '', '', '', 'Script to transform text in a list of sentences', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['google scripts', 43, 1, 'us', '', '', '', '', '', '', 'Google App scripts to replicate Dynamic Scheduling in Google Sheets', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['google sheets', 44, 1, 'cn', '', '', '', '', '', '', 'Google App scripts to replicate Dynamic Scheduling in Google Sheets', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['graph', 45, 1, 'cn', '', '', '', '', '', '', 'Visualize Friend Interactions', '', '', '', '', '', '', 3, 'es', 'gb', 'cn', '', '', '', '', 'SOAP to REST converter', 'Neo4j Graph Database', 'Graph Theory Tutor', '', '', '', '', ],
['graphics', 46, 1, 'ca', '', '', '', '', '', '', 'W3AI Communication materials', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['graphs', 47, 1, 'ro', '', '', '', '', '', '', 'Find all isomorphisms of a graph', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['group', 48, 1, 'hu', '', '', '', '', '', '', 'W3AI Communication materials', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['gs', 49, 1, 'ru', '', '', '', '', '', '', 'Google Social DNA Editor', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['gs', 50, 1, 'it', '', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['images', 51, 2, 'il', 'pt', '', '', '', '', '', 'W3AI favicon', 'W3AI Logo', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['international', 52, 1, 'gb', '', '', '', '', '', '', 'W3AI organization structure like W3C', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['introduction', 53, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'cn', '', '', '', '', '', '', 'Social DNA consulting', '', '', '', '', '', '', ],
['java', 54, 1, 'ca', '', '', '', '', '', '', 'JIRA Issues translator to Social DNA', '', '', '', '', '', '', 3, 'ru', 'de', 'in', '', '', '', '', 'Swagger Generator', 'Vertx Developer', 'SOAP to REST converter', '', '', '', '', ],
['Java', 55, 1, 'ca', '', '', '', '', '', '', 'Visualize Friend Interactions', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['javascript', 56, 1, 'ru', '', '', '', '', '', '', 'JIRA Issues translator to Social DNA', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['js', 57, 1, 'cn', '', '', '', '', '', '', 'JS timer function to change DOM text', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['legal', 58, 1, 'cn', '', '', '', '', '', '', 'W3AI organization structure like W3C', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['letter', 59, 1, 'es', '', '', '', '', '', '', 'Einstein to POTUS letter transformation', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['list', 60, 1, 'us', '', '', '', '', '', '', 'Script to transform text in a list of sentences', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['logo', 61, 1, 'ca', '', '', '', '', '', '', 'W3AI Logo', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['math', 62, 1, 'ca', '', '', '', '', '', '', 'Find all isomorphisms of a graph', '', '', '', '', '', '', 1, 'us', '', '', '', '', '', '', 'Graph Theory Tutor', '', '', '', '', '', '', ],
['messages', 63, 1, 'ru', '', '', '', '', '', '', 'Project team communication', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['microsoft', 64, 1, 'cn', '', '', '', '', '', '', 'Mobile Social DNA Editor for Office 365', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['mobile', 65, 2, 'cn', 'ca', '', '', '', '', '', 'test', 'Google Social DNA Editor', '', '', '', '', '', 1, 'ca', '', '', '', '', '', '', 'website generator', '', '', '', '', '', '', ],
['noun', 66, 2, 'es', 'tr', '', '', '', '', '', 'Google Sheets Social DNA noun template', 'Excel Social DNA noun template', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['office', 67, 1, 'us', '', '', '', '', '', '', 'Mobile Social DNA Editor for Office 365', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['organization', 68, 1, 'br', '', '', '', '', '', '', 'W3AI organization structure like W3C', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['organizers', 69, 1, 'ca', '', '', '', '', '', '', 'W3AI Communication materials', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['page', 70, 1, 'ca', '', '', '', '', '', '', 'About Social DNA Language', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['plan', 71, 1, 'us', '', '', '', '', '', '', 'W3AI Communication materials', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['planning', 72, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'cn', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['Postgres', 73, 1, 'fr', '', '', '', '', '', '', 'Create REST API for Postgres Database', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['registration', 74, 1, 'de', '', '', '', '', '', '', 'W3AI organization structure like W3C', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['REST', 75, 1, 'ca', '', '', '', '', '', '', 'Create REST API for Postgres Database', '', '', '', '', '', '', 3, 'in', 'hu', 'cn', '', '', '', '', 'Swagger Generator', 'SOAP to REST converter', 'Neo4j Graph Database', '', '', '', '', ],
['scheduling', 76, 1, 'cn', '', '', '', '', '', '', 'Google App scripts to replicate Dynamic Scheduling in Google Sheets', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['script', 77, 2, 'ca', 'tr', '', '', '', '', '', 'Google Sheets Social DNA verb template', 'Google Sheets Social DNA noun template', '', '', '', '', '', 1, 'jp', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['script', 78, 2, 'us', 'de', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', 'Script to transform text in a list of sentences', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['scripting', 79, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'fr', '', '', '', '', '', '', 'Agile planning automation scripts', '', '', '', '', '', '', ],
['scripts', 80, 4, 'cn', 'ca', 'ca', 'hu', 'it', '', '', 'W3AI Communication materials', 'Microsoft Project translator to Social DNA', 'Google Social DNA Editor', 'Mobile Social DNA Editor for Office 365', '', '', '', 2, 'mx', 'it', '', '', '', '', '', 'DevOps scripts templating', 'Social DNA consulting', '', '', '', '', '', ],
['sdna', 81, 3, 'ru', 'tr', 'fr', '', '', '', '', 'Google Sheets Social DNA noun template', 'Social DNA Translator to SQL Google', 'Excel Social DNA noun template', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['sell', 82, 1, 'ca', '', '', '', '', '', '', 'Secret sauce sell 4 liters', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['sentence', 83, 1, 'eg', '', '', '', '', '', '', 'Script to transform text in a list of sentences', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['sentence', 84, 1, 'in', '', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['service', 85, 1, 'cn', '', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['services', 86, 1, 'pl', '', '', '', '', '', '', 'JIRA Issues translator to Social DNA', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['sheets', 87, 2, 'pt', 'in', '', '', '', '', '', 'Google Sheets Social DNA verb template', 'Google Sheets Social DNA noun template', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['simple', 88, 2, 'tr', 'gb', '', '', '', '', '', '3 Jars', 'Large Pizza, 3 Toppings', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['skills', 89, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'il', '', '', '', '', '', '', 'Social DNA consulting', '', '', '', '', '', '', ],
['SOAP', 90, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'es', '', '', '', '', '', '', 'SOAP to REST converter', '', '', '', '', '', '', ],
['social', 91, 1, 'ca', '', '', '', '', '', '', 'Visualize Friend Interactions', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['software', 92, 3, 'tr', 'fr', 'in', '', '', '', '', 'Microsoft Project translator to Social DNA', 'Google Social DNA Editor', 'Mobile Social DNA Editor for Office 365', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['sql', 93, 1, 'hu', '', '', '', '', '', '', 'Social DNA Translator to SQL Google', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['tags', 94, 1, 'ro', '', '', '', '', '', '', 'Add counter of clicks for activation tags', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['team', 95, 1, 'us', '', '', '', '', '', '', 'New agile team trust', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['template', 96, 4, 'ca', 'es', 'in', 'ru', '', '', '', 'Google Sheets Social DNA verb template', 'Google Sheets Social DNA noun template', 'Excel Social DNA verb template', 'Excel Social DNA noun template', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['templates', 97, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'ca', '', '', '', '', '', '', 'DevOps scripts templating', '', '', '', '', '', '', ],
['testing', 98, 1, 'br', '', '', '', '', '', '', 'Create archive from the problems entered this weekend', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['time managment', 99, 1, 'pt', '', '', '', '', '', '', 'Arrive on time', '', '', '', '', '', '', 1, 'br', '', '', '', '', '', '', 'leave early', '', '', '', '', '', '', ],
['timer', 100, 1, 'ca', '', '', '', '', '', '', 'JS timer function to change DOM text', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['tokens', 101, 1, 'cn', '', '', '', '', '', '', 'Tokenize a sentence in Google Apps Script', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['trainings', 102, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'my', '', '', '', '', '', '', 'Social DNA consulting', '', '', '', '', '', '', ],
['transformation', 103, 1, 'us', '', '', '', '', '', '', 'Einstein to POTUS letter transformation', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['translator', 104, 3, 'us', 'cn', 'ru', '', '', '', '', 'JIRA Issues translator to Social DNA', 'Social DNA Translator to SQL Google', 'Microsoft Project translator to Social DNA', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['trust', 105, 1, 'ca', '', '', '', '', '', '', 'New agile team trust', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['vba', 106, 3, 'us', 'it', 'cn', '', '', '', '', 'Microsoft Project translator to Social DNA', 'Excel Social DNA noun template', 'Mobile Social DNA Editor for Office 365', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['vertx', 107, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 'bd', '', '', '', '', '', '', 'Vertx Developer', '', '', '', '', '', '', ],
['visual', 108, 1, 'cn', '', '', '', '', '', '', 'Visualize Friend Interactions', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['w3ai', 109, 3, 'pt', 'in', 'es', '', '', '', '', 'W3AI organization structure like W3C', 'W3AI favicon', 'W3AI Logo', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ],
['web', 110, 6, 'ro', 'fr', 'ru', 'cn', 'es', 'us', '', 'Digital Front end display for ShiftKey Labs', '3 Jars', 'mobile ready forms', 'Create REST API for Postgres Database', 'About Social DNA Language', 'Visualize Friend Interactions', '', 6, 'sa', 'cn', 'ca', 'pk', 'vn', 'gr', '', 'Swagger Generator', 'Vertx Developer', 'MySQL Database Admin', 'website generator', 'SOAP to REST converter', 'Neo4j Graph Database', '', ],
['wrd', 111, 1, 'us', '', '', '', '', '', '', 'New agile team trust', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', ]
];

// export Algo Queue
export {queue};